"use strict";

const CONFIG={sheetId:"1xhyDHmOjeDFh0EDZkwiQX0N-GB4DYhqu2WVtuHqKqok",sheetGid:"2037124561",appFeedUrl:"https://afb-internal.co.uk/api/tv-feed",refreshMs:300000,rotateMs:15000,timeZone:"Europe/London"};
const SCREENS=["overview","availability","operations"];
const BARNS=["Walnut House","Rowan House","Chestnut House","Lindum Barn","Eastgate Barn","Field Maple Barn","Holly Tree Barn","Red Oak Barn","Wild Cherry Barn","Meadowsweet Barn","The Birches","The Elms","The Hazels","The Pines","The Sycamores","The Willows","Blue Iris Cottage","Dragonfly Cottage","Mallard Cottage","Marsh Marigold Cottage","Water Lily Cottage","White Swan Cottage","Bailgate Barn","Castle Hill Barn"];
const FALLBACK_TUBS=[
 ["Walnut House",37.1,31,"READY","ON",6,"29/09/25"],["Rowan House",35.4,31,"READY","ON",13,"Never"],["Chestnut House",37.9,31,"READY","ON",13,"08/10/25"],["Lindum Barn",38.5,31,"READY","ON",6,"Never"],["Eastgate Barn",35.1,31,"READY","ON",10,"06/11/25"],["Field Maple Barn",36.5,31,"READY","ON",12,"22/10/25"],["Holly Tree Barn",32.5,31,"READY","ON",24,"Never"],["Red Oak Barn",36.3,31,"READY","ON",24,"Never"],["Wild Cherry Barn",38.9,31,"READY","ON",19,"Never"],["Meadowsweet Barn",36.4,31,"READY","ON",24,"04/12/25"],["The Birches",38.2,31,"READY","ON",3,"03/02/26"],["The Elms",38.4,31,"READY","ON",12,"Check date"],["The Hazels",37.4,31,"READY","ON",12,"24/02/26"],["The Pines",37.2,31,"READY","ON",17,"13/11/25"],["The Sycamores",33.8,31,"READY","ON",17,"11/12/25"],["The Willows",37.3,31,"READY","ON",12,"Never"]
];
let nextRefresh=Date.now()+CONFIG.refreshMs,lastMatrix=null,currentScreen=0,rotationTimer;
const $=id=>document.getElementById(id);
const text=(id,value)=>{const el=$(id);if(el&&value!==undefined&&value!==null&&value!=="")el.textContent=value};
const normalize=v=>String(v??"").trim();
const norm=v=>normalize(v).toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const escapeHtml=value=>normalize(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);

function captureTvToken(){const url=new URL(window.location.href),token=url.searchParams.get("tv_token");if(!token)return;localStorage.setItem("afbTvToken",token);url.searchParams.delete("tv_token");history.replaceState({},"",`${url.pathname}${url.search}${url.hash}`)}

function updateClock(){const now=new Date();text("clock",new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false,timeZone:CONFIG.timeZone}).format(now));text("date",new Intl.DateTimeFormat("en-GB",{weekday:"short",day:"numeric",month:"long",year:"numeric",timeZone:CONFIG.timeZone}).format(now));text("todayLabel",new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long",timeZone:CONFIG.timeZone}).format(now));const s=Math.max(0,Math.floor((nextRefresh-Date.now())/1000));text("refreshCountdown",`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`)}
function setScreen(name,manual=false){document.querySelectorAll(".screen-tab").forEach(b=>b.classList.toggle("active",b.dataset.screen===name));SCREENS.forEach(screen=>$(screen+"Screen").classList.toggle("active",name===screen));currentScreen=Math.max(0,SCREENS.indexOf(name));if(manual)restartRotation()}
function restartRotation(){clearInterval(rotationTimer);rotationTimer=setInterval(()=>setScreen(SCREENS[(currentScreen+1)%SCREENS.length]),CONFIG.rotateMs)}
document.querySelectorAll(".screen-tab").forEach(b=>b.addEventListener("click",()=>setScreen(b.dataset.screen,true)));

function renderTubs(rows){const body=$("hotTubTable").querySelector("tbody");body.innerHTML="";const display=rows.slice(0,16);display.forEach(r=>{const temp=parseFloat(r[1]);const tr=document.createElement("tr");const tempClass=!Number.isFinite(temp)?"":temp>=40?"temp-bad":temp<34?"temp-warn":"temp-good";const statusClass=/ready|ok/i.test(r[3])?"status-ready":"status-action";tr.innerHTML=`<td>${r[0]}</td><td class="${tempClass}">${r[1]??"–"}</td><td>${r[2]??"–"}</td><td class="${statusClass}">${r[3]||"–"}</td><td>${r[4]||"–"}</td><td>${r[5]??"–"}</td><td class="${/never|check/i.test(r[6])?"service-overdue":""}">${r[6]||"–"}</td>`;body.appendChild(tr)});const ready=rows.filter(r=>/ready|ok/i.test(r[3])).length;const actions=rows.filter(r=>!/ready|ok/i.test(r[3])||parseFloat(r[1])>=40||String(r[4]).toUpperCase()!=="ON").length;text("hotTubReady",actions?`${actions} need attention`:`${ready} monitored tubs ready`);text("tubFooter",actions?`${actions} monitored hot tubs need attention`:`All ${ready} monitored hot tubs ready`);text("hotTubText",actions?`${actions} require attention`:"All monitored tubs normal");text("tubPanelBadge",`${rows.length} monitored`);renderTubActions(rows)}
function renderTubActions(rows){const actions=rows.filter(r=>!/ready|ok/i.test(r[3])||parseFloat(r[1])>=40||String(r[4]).toUpperCase()!=="ON");const box=$("tubActionList");if(box)box.innerHTML=actions.length?actions.slice(0,7).map(r=>`<div class="large-action"><strong>${r[0]}</strong><span>${r[3]||"CHECK"} • ${r[1]||"–"}°C • Pump ${r[4]||"–"}</span></div>`).join(""):"<div class='large-action'><strong>All tubs reporting normally</strong><span>No immediate action required</span></div>";text("tubActionRibbon",actions.length?`${actions.length} hot tub actions required`:"No hot tub changes needed")}
function defaultAvailability(){const now=new Date();const dates=Array.from({length:18},(_,i)=>{const d=new Date(now);d.setDate(d.getDate()+i-3);return d});return {dates,rows:BARNS.map((b,bi)=>[b,...dates.map((_,di)=>{if((bi+di)%7===2)return"OUT 10:00 / IN 15:00";if((bi+di)%11===5)return"AVAILABLE";return"BOOKED"})])}}
function calendarCell(value){const raw=normalize(value),n=norm(raw),hasOut=/\bout\b/.test(n),hasIn=/\bin\b/.test(n),maintenance=/maintenance|blocked|deep clean|repair|service|owner/.test(n);let cls="cell-free";if(maintenance)cls="cell-maintenance";else if(hasOut&&hasIn)cls="cell-turn";else if(hasOut)cls="cell-checkout";else if(hasIn)cls="cell-checkin";else if(/booked|occupied/.test(n))cls="cell-booked";else if(/fault|offline|action/.test(n))cls="cell-fault";const parts=raw?raw.split(/\s*\/\s*/):["–"];const content=parts.map(part=>{const p=normalize(part),lateOut=/\bOUT\s+(?!10:00)\d{1,2}:\d{2}/i.test(p),earlyIn=/\bIN\s+(?!15:00)\d{1,2}:\d{2}/i.test(p);return`<span class="calendar-event${lateOut||earlyIn?" exception-time":""}">${escapeHtml(p||"–")}</span>`}).join("");return`<td class="${cls}">${content}</td>`}
function renderAvailability(data){const table=$("availabilityTable"),head=table.querySelector("thead"),body=table.querySelector("tbody");head.innerHTML=`<tr><th>Barn</th>${data.dates.map(d=>`<th>${d instanceof Date?new Intl.DateTimeFormat("en-GB",{weekday:"short",day:"2-digit",month:"2-digit"}).format(d):escapeHtml(d)}</th>`).join("")}</tr>`;body.innerHTML=data.rows.slice(0,24).map(r=>`<tr><td>${escapeHtml(r[0])}</td>${r.slice(1,data.dates.length+1).map(calendarCell).join("")}</tr>`).join("")}

function matrixFromResponse(response){return (response?.table?.rows||[]).map(row=>(row.c||[]).map(cell=>cell?(cell.f??cell.v??""):""))}
function findHeader(matrix,terms){return matrix.findIndex(row=>terms.every(t=>row.some(v=>norm(v).includes(t))))}
function columnIndex(row,aliases){return row.findIndex(v=>aliases.some(a=>norm(v).includes(a)))}
function parseTubRows(matrix){const ri=findHeader(matrix,["barn","hot tub temp"]);if(ri<0)return[];const h=matrix[ri],ix={barn:columnIndex(h,["barn"]),temp:columnIndex(h,["hot tub temp"]),set:columnIndex(h,["set temp"]),status:columnIndex(h,["tub status","status"]),pump:columnIndex(h,["pump"]),refill:columnIndex(h,["refill age","days since"]),service:columnIndex(h,["last service"])};const rows=[];for(let i=ri+1;i<matrix.length;i++){const r=matrix[i],barn=normalize(r[ix.barn]);if(!barn){if(rows.length)break;continue}if(!BARNS.some(b=>norm(b)===norm(barn))){if(rows.length)break;continue}rows.push([barn,r[ix.temp],r[ix.set],r[ix.status],r[ix.pump],r[ix.refill],r[ix.service]])}return rows}
function numeric(v){const s=normalize(v).replace(/,/g,"");return /^-?\d+(\.\d+)?$/.test(s)?Number(s):null}
function findNumericNear(matrix,labelAliases){for(let r=0;r<matrix.length;r++)for(let c=0;c<matrix[r].length;c++){const n=norm(matrix[r][c]);if(labelAliases.some(a=>n===a)){const positions=[[r+1,c],[r,c+1],[r+1,c+1],[r,c+2],[r+2,c]];for(const [rr,cc] of positions){const value=numeric(matrix[rr]?.[cc]);if(value!==null)return value}}}return null}
function findSection(matrix,title,required){const hits=[];matrix.forEach((row,r)=>row.forEach((v,c)=>{if(norm(v)===title)hits.push({r,c})}));return hits.find(hit=>required.every(label=>matrix.slice(hit.r,hit.r+16).some(row=>row.slice(hit.c,hit.c+10).some(v=>norm(v)===label))))||null}
function sectionNumber(matrix,section,label){if(!section)return null;for(let r=section.r;r<Math.min(matrix.length,section.r+16);r++)for(let c=section.c;c<Math.min(matrix[r].length,section.c+10);c++)if(norm(matrix[r][c])===label){for(let cc=c+1;cc<Math.min(matrix[r].length,section.c+10);cc++){const v=numeric(matrix[r][cc]);if(v!==null)return v}for(let rr=r+1;rr<Math.min(matrix.length,r+3);rr++){const v=numeric(matrix[rr]?.[c]);if(v!==null)return v}}return null}
function extractMaintenanceTasks(matrix){const tasks=[];matrix.forEach(row=>{const joined=row.map(normalize).filter(Boolean);if(!joined.some(v=>/overdue/i.test(v)))return;const barn=joined.find(v=>BARNS.some(b=>norm(b)===norm(v)));if(!barn)return;const task=joined.find(v=>v!==barn&&!/overdue|\d{1,2}[\/\-]\d{1,2}|^\d+$|days?/i.test(v));const age=joined.find(v=>/overdue/i.test(v))||"Overdue";if(task)tasks.push({barn,task,age})});return tasks.slice(0,5)}
function renderMaintenanceTasks(tasks,overdue){if(tasks.length){const first=tasks[0];text("priorityBarn",first.barn);text("priorityTask",first.task);text("maintenanceBarn",first.barn);text("maintenanceTask",first.task);text("maintenanceAge",first.age);$("nextActions").innerHTML=tasks.map(t=>`<div class="next-action"><strong>${t.task}</strong><span>${t.barn}</span><b>${t.age}</b></div>`).join("")}else if(overdue>0){text("priorityBarn",`${overdue} overdue items`);text("priorityTask","Open maintenance task list");text("maintenanceBarn",`${overdue} overdue items`);text("maintenanceTask","See maintenance manager");$("nextActions").innerHTML="<p>Open the maintenance manager for the overdue list.</p>"}else{text("priorityBarn","No overdue tasks");text("priorityTask","Maintenance is up to date");text("maintenanceBarn","No overdue tasks");text("maintenanceTask","Nothing urgent");text("maintenanceAge","");$("nextActions").innerHTML="<p>No overdue maintenance actions.</p>"}}
function parseMetrics(matrix){const daily={checkIns:["check ins"],checkOuts:["check outs"],changeovers:["changeovers"],earlyCheckIns:["early check ins"],lateCheckOuts:["late check outs"],ttSetups:["tt setups"]};Object.entries(daily).forEach(([id,a])=>{const v=findNumericNear(matrix,a);if(v!==null)text(id,v)});const maintenance=findSection(matrix,"maintenance",["total items","due this month"]),pat=findSection(matrix,"pat testing",["total items","failed"]);const maintenanceMap={maintenanceTotal:"total items",maintenanceOverdue:"overdue",maintenanceThisMonth:"due this month",maintenanceNextMonth:"due next month",maintenanceSoon:"due soon"},patMap={patTotal:"total items",patFailed:"failed",patOverdue:"overdue",patSoon:"due soon"};Object.entries(maintenanceMap).forEach(([id,label])=>{const v=sectionNumber(matrix,maintenance,label);if(v!==null)text(id,v)});Object.entries(patMap).forEach(([id,label])=>{const v=sectionNumber(matrix,pat,label);if(v!==null)text(id,v)});const overdue=Number($("maintenanceOverdue").textContent)||0;text("maintenanceJobs",overdue);text("maintenanceText",overdue?`${overdue} overdue`:"No overdue items");renderMaintenanceTasks(extractMaintenanceTasks(matrix),overdue)}
function parseAvailability(matrix){const candidates=[];matrix.forEach((row,i)=>{const barn=columnIndex(row,["barn"]);if(barn>=0){const dateCells=row.slice(barn+1).filter(v=>/\d{1,2}[\/\-]\d{1,2}|mon|tue|wed|thu|fri|sat|sun/i.test(normalize(v)));if(dateCells.length>=5)candidates.push({i,barn,row})}});if(!candidates.length)return null;const h=candidates[0],firstDate=h.row.findIndex((v,index)=>index>h.barn&&/\d{1,2}[\/\-]\d{1,2}|mon|tue|wed|thu|fri|sat|sun/i.test(normalize(v)));if(firstDate<0)return null;const dates=h.row.slice(firstDate).filter(v=>normalize(v));const rows=[];for(let i=h.i+1;i<matrix.length;i++){const r=matrix[i],barn=normalize(r[h.barn]);if(!BARNS.some(b=>norm(b)===norm(barn))){if(rows.length)break;continue}rows.push([barn,...r.slice(firstDate,firstDate+dates.length)])}return rows.length?{dates,rows}:null}
function renderCleaningStatus(matrix){const ri=findHeader(matrix,["barn","cleaning status"]);if(ri<0)return;const h=matrix[ri],barnIndex=columnIndex(h,["barn"]),statusIndex=columnIndex(h,["cleaning status"]),needs=[];for(let i=ri+1;i<matrix.length;i++){const row=matrix[i],barn=normalize(row[barnIndex]);if(!BARNS.some(name=>norm(name)===norm(barn))){if(needs.length||i>ri+24)break;continue}if(/not cleaned|needs cleaning|requires cleaning|^pc\b|part clean/.test(norm(row[statusIndex])))needs.push(barn)}text("cleaningCount",needs.length);text("cleaningText",needs.length?`${needs.slice(0,2).join(", ")}${needs.length>2?" + more":""}`:"All cleaning complete");text("cleaningRibbon",needs.length?`Cleaning required: ${needs.length}`:"Cleaning complete")}
function applyLiveData(matrix){lastMatrix=matrix;const tubs=parseTubRows(matrix),availability=parseAvailability(matrix)||defaultAvailability();renderTubs(tubs.length?tubs:FALLBACK_TUBS);renderAvailability(availability);renderCleaningStatus(matrix);parseMetrics(matrix);text("dataStatus","Live Google Sheet connected");text("sourceState","Live");text("lastUpdated",`Updated ${new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date())}`);$("systemState").classList.remove("offline")}
function loadSheet(){nextRefresh=Date.now()+CONFIG.refreshMs;text("dataStatus","Refreshing live Google Sheet…");const old=document.getElementById("sheetLoader");if(old)old.remove();const script=document.createElement("script");script.id="sheetLoader";script.src=`https://docs.google.com/spreadsheets/d/${CONFIG.sheetId}/gviz/tq?gid=${CONFIG.sheetGid}&headers=0&tqx=responseHandler:afbSheetLoaded&_=${Date.now()}`;script.onerror=()=>{text("dataStatus","Live connection retrying — showing last data");text("sourceState","Retrying");if(!lastMatrix){renderTubs(FALLBACK_TUBS);renderAvailability(defaultAvailability())}};document.head.appendChild(script)}
window.afbSheetLoaded=response=>{if(response?.status==="error"){text("dataStatus","Sheet access needs checking — showing last data");return}applyLiveData(matrixFromResponse(response))};
function formatTime(value){if(!value)return"";const d=new Date(value);return Number.isNaN(d.getTime())?"":new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:CONFIG.timeZone}).format(d)}
function renderOpsList(id,items,emptyText,render){const box=$(id);box.innerHTML=items.length?items.map(render).join(""):`<div class="ops-empty">${escapeHtml(emptyText)}</div>`}
function renderAppFeed(feed){const checkedIn=Array.isArray(feed.checkedIn)?feed.checkedIn:[],bbqs=Array.isArray(feed.bbqs)?feed.bbqs:[],lockouts=Array.isArray(feed.lockouts)?feed.lockouts:[],urgent=Array.isArray(feed.urgentMaintenance)?feed.urgentMaintenance:[];text("staffCount",checkedIn.length);text("bbqCount",bbqs.length);text("lockoutCount",lockouts.length);text("urgentCount",urgent.length);text("morningCheckCount",feed.checks?.morning??0);text("afternoonCheckCount",feed.checks?.afternoon??0);renderOpsList("checkedInList",checkedIn,"No outside staff checked in",item=>`<div class="ops-row"><strong>${escapeHtml(item.firstName||"Staff member")}</strong><span>Since ${escapeHtml(formatTime(item.clockInAt)||"earlier today")}</span></div>`);renderOpsList("bbqList",bbqs,"No BBQs reported for cleaning",item=>`<div class="ops-row"><strong>${escapeHtml(item.location||"Barn")}</strong><span>Reported ${escapeHtml(formatTime(item.reportedAt)||"today")}</span></div>`);renderOpsList("lockoutList",lockouts,"No hot tubs on lockout",item=>`<div class="ops-row danger"><strong>${escapeHtml(item.barn||"Hot tub")}</strong><span>Locked out</span></div>`);renderOpsList("urgentList",urgent,"No urgent maintenance jobs",item=>`<div class="ops-row ${norm(item.priority)==="urgent"?"danger":"warn"}"><strong>${escapeHtml(item.barn||item.category||"Site")}</strong><span>${escapeHtml(item.description||item.category||"Maintenance required")}</span><b>${escapeHtml(item.priority||"High")}</b></div>`);text("appFeedState","Secure AFB Staff connection live");text("appFeedUpdated",`Updated ${formatTime(feed.updatedAt)||formatTime(new Date())}`)}
async function loadAppFeed(){const token=localStorage.getItem("afbTvToken");if(!token){$("tvSetupState").hidden=false;$("operationsContent").hidden=true;text("appFeedState","TV setup required");text("appFeedUpdated","");return}try{const response=await fetch(CONFIG.appFeedUrl,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(response.status===401){localStorage.removeItem("afbTvToken");$("tvSetupState").hidden=false;$("operationsContent").hidden=true;text("appFeedState","TV access needs renewing");return}if(!response.ok)throw new Error("Feed unavailable");const feed=await response.json();$("tvSetupState").hidden=true;$("operationsContent").hidden=false;renderAppFeed(feed)}catch{$("tvSetupState").hidden=true;$("operationsContent").hidden=false;text("appFeedState","AFB Staff connection retrying");text("appFeedUpdated","Showing last secure update")}}
async function loadWeather(){try{const r=await fetch("https://api.open-meteo.com/v1/forecast?latitude=53.27&longitude=-0.47&current=temperature_2m,weather_code&timezone=Europe%2FLondon");const j=await r.json(),c=j.current||{},code=Number(c.weather_code);text("weatherTemp",`${Math.round(c.temperature_2m)}°C`);text("weatherText",code===0?"Clear":code<4?"Partly cloudy":code<60?"Cloudy":code<80?"Rain":"Showers");text("weatherIcon",code===0?"☀":"◐")}catch{text("weatherText","Lincoln")}}
window.addEventListener("online",()=>{text("internetState","Connected");loadSheet();loadAppFeed()});window.addEventListener("offline",()=>{text("internetState","Offline");text("sourceState","Last data")});
captureTvToken();renderTubs(FALLBACK_TUBS);renderAvailability(defaultAvailability());updateClock();setInterval(updateClock,1000);restartRotation();loadWeather();loadSheet();loadAppFeed();setInterval(()=>{loadSheet();loadAppFeed()},CONFIG.refreshMs);
